data:
  raw: data/raw/odor.csv
  processed: data/processed
 
column:
  smile: ["nonStereoSMILES"]
  drop: ['descriptors']

train_path: data/processed/train_dataset.pkl
test_path: data/processed/test_dataset.pkl